name: JavaScript CI with Mocha

on:
  # Trigger the workflow on push and pull request events
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    # Run on different operating systems and Node.js versions for comprehensive testing
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Setup Node.js with the matrix-defined version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Run tests using Mocha, specifying the tests/ directory
      - name: Run Mocha tests
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install --verbose --fetch-timeout 600000